m.91cpcar.com/Controllers/CommonController.cs
using ActiveModule;
using OrderModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace m._91cpcar.com.Controllers
{
    public class CommonController : Controller
    {
        OrderBuss obbll = new OrderBuss();
        VoucherBus vbll = new VoucherBus();
        // GET: /Common/
        public ActionResult PayOrder(string oid)
        {
            if (Session["memberID"] != null)
            {
                int uid = Convert.ToInt32(Session["memberID"]);
                PayOrderOM outMode = new PayOrderOM();
                outMode.voucher = vbll.GetVoucherByUid(uid, 0);//用户可以使用的优惠券
                if (!string.IsNullOrEmpty(oid))
                {
                    outMode.order = obbll.GetOrder(oid);
                }
                return View(outMode);
            }
            else
            {
                return RedirectToAction("Login", "member");
            }
        }

        [HttpPost]
        public ActionResult PayOrder(PayOrderModel o)
        {
            try
            {
                if (Session["memberID"] != null)
                {
                    int uid = Convert.ToInt32(Session["memberID"]);
                    List<DAO.OrderPay> ol = new List<DAO.OrderPay>();
                    DAO.Order order = obbll.GetOrder(o.oid);
                    decimal totle = order.TotalPrice;
                    decimal dis = 0;
                    decimal payprice = 0;
                    if (!string.IsNullOrEmpty(o.coupon))//复合付款有优惠券
                    {
                        //验证优惠券
                        DAO.Voucher voucher = vbll.GetVoucherModel(uid, o.coupon, 0);
                        if (voucher == null)
                        {
                            return Json(new { r = "error", msg = "优惠券验证失败！" });
                        }
                        else
                        {

                            dis = voucher.Price;//优惠券优惠金额
                            DAO.OrderPay io = new DAO.OrderPay();
                            io.Amount = dis;
                            io.Bank = "优惠券";
                            io.OrderId = o.oid;
                            io.OrderType = o.ordertype;
                            io.PayState = "未支付";
                            io.PayType = 1;//直接支付1优惠券
                            io.RecordState = 1;
                            io.Uid = Convert.ToInt32(Session["memberID"]);
                            io.Remark = voucher.VoucherNumber;
                            ol.Add(io);
                        }
                    }
                    payprice = totle - dis;
                    if (payprice > 0)
                    {
                        DAO.OrderPay io = new DAO.OrderPay();
                        io.Amount = payprice;
                        if (o.paytype == "alipay")
                        {
                            io.Bank = "支付宝";
                        }
                        if (o.paytype == "weixin")
                        {
                            io.Bank = "微信";
                        }
                        io.OrderId = o.oid;
                        io.OrderType = o.ordertype;
                        io.PayState = "未支付";
                        io.PayType = 0;//直接支付1优惠券
                        io.RecordState = 1;
                        io.Uid = Convert.ToInt32(Session["memberID"]);
                        ol.Add(io);
                    }
                    bool r = obbll.AddOrderPay(o.oid, ol);
                    return Json(new { r = "ok" });
                }
                else
                {
                    return Json(new { r = "nologin" });
                }
            }
            catch (Exception e)
            {
                return Json(new { r = "error", msg = "异常：" + e.Message });
            }
        }
    }
    public class PayOrderOM
    {
        public DAO.Order order { get; set; }
        public List<DAO.Voucher> voucher { get; set; }
    }
    public class PayOrderModel
    {
        public string oid { get; set; }//订单号
        public string paytype { get; set; }//支付类型
        public decimal payprice { get; set; }//支付价格
        public string coupon { get; set; }//优惠券号
        public decimal couponprice { get; set; }//优惠金额
        public int ordertype { get; set; }
    }
}

m.91cpcar.com/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>   
  <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />  
    <meta name="keywords" content="诚配,诚配改装,汽车改装,改装件,汽车配件,海外配件,进口配件,保时捷,宝马,奔驰,法拉利,豪车改装,高端改装">
    <meta name="description" content="">   <meta  />
       <link href="/content/css/mui.css" rel="stylesheet" />
     <link href="/content/css/main.css" rel="stylesheet" />
		<style type="text/css">
			#list {
				/*避免导航边框和列表背景边框重叠，看起来像两条边框似得；*/
				margin-top: -1px;               
			}
		</style>
    @RenderSection("styles", required: false)  
    <script>
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "//hm.baidu.com/hm.js?d252ab9e4e87638601460ea0c7412a01";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
</script>
</head>
<body>
     <div id="modal-bg"></div>
    <div id="modal-show">
       <img  src="/content/img/ico/loading.gif"/>
    </div>
  
    <div class="main-container">@RenderBody()</div>
    @if (ViewBag.isFoot == null || ViewBag.isFoot)
    {
   <footer class="pfoot">		
		<!--<div class="ui-footer-version">
        <p>我们在致力于打造中国最齐全的汽车改装配件市场!诚配改装网是汽车改装配件电商平台.
我们能为您快速查找您需要的改装配件，同时提供最放心的交易平台</p>        	
        </div>-->
		<!--<div class="ui-footer-version">
        
        	<a class="txt-grey-3" href="http://www.91cpcar.com">电脑版</a>
            <a class="txt-grey-3" href="http://m.91cpcar.com">触屏版</a>
            <a class="txt-grey-3" href="#">客户端</a>
        </div>-->
        <div class="ui-footer-version">        
        <p>Copyring @@ 2015 诚配91CPCAR.com  版权所有 <br> 湘ICP备15020410号  </p>
        </div>
  
	</footer>
    }
</body>
</html>
  <script src="/content/js/mui.min.js"></script>
 <script src="~/Content/js/zepto.min.js"></script>
<script src="~/Content/js/zepto.cookie.js"></script>
<script src="~/Content/js/Base.js"></script>
 @RenderSection("scripts", required: false)  
<script>
    if (Validata.IsPC()) {
      //  window.location.href = "http://www.91cpcar.com";
    } 
</script>

m.91cpcar.com/Views/Shared/_LayoutNoBa.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>   
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">   
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="keywords" content="诚配,诚配改装,汽车改装,改装件,汽车配件,海外配件,进口配件,保时捷,宝马,奔驰,法拉利,豪车改装,高端改装">
    <meta name="description" content="">
    <meta  />
    <!--打包的js-->
    @System.Web.Optimization.Scripts.Render("~/Content/jslib")
    @System.Web.Optimization.Scripts.Render("~/bundles/js")
    <!--打包的css-->
    @System.Web.Optimization.Styles.Render("~/Content/csslib")
   
    @RenderSection("styles", required: false)
    
  <script>
      var _hmt = _hmt || [];
      (function () {
          var hm = document.createElement("script");
          hm.src = "//hm.baidu.com/hm.js?d252ab9e4e87638601460ea0c7412a01";
          var s = document.getElementsByTagName("script")[0];
          s.parentNode.insertBefore(hm, s);
      })();
</script>
</head>
<body>
     <div class="body">
        <div class="head">
            <div class="logo left"><a href="/index2.html">
              <img src="/content/img/logo.png" /></a><img src="/content/img/slogo.png" class="slogo"/></div>
                 <div class="hGsearch left">
                <div class="hGgsearch center" >
                       <img src="/content/img/searchbutton.jpg" class="right" id="topsearch"/>
                    <div class="right"><input type="text" class="txt_search " id="txt_keyword" /></div>
                    <div style="clear:both"></div>          
                </div>
            </div>
               <div class="left" style="padding-top: 30px">
                <a href="/Car/index" class="btn btn-default" style="font-size: 16px">
                    <span class="glyphicon glyphicon-shopping-cart" style="">购物车共<span style="color: red; font-size: 20px" id="hcarnum">0</span>项</span>
                </a>
            </div>
            <div class="left" style="padding-left: 10px;">
               <div style="font-size: 16px; padding-top: 10px; padding-bottom: 6px;" id="nologinAre">
                    &nbsp; <a href="/member/Login">登录</a> | <a href="/Member/RegView">注册</a><br />
                </div>
                 <div style="font-size: 16px; padding-top: 10px; padding-bottom: 6px; display:none" id="loginAre">
                    &nbsp; <a href="/member/LoginOut">退出登录</a> <br />
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle"
                        data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span>我的账户 <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                         <li><a href="/Member/UserHome">账户信息</a></li>
                        <li class="divider"></li>
                        <li><a href="/Member/MyOrder">我的订单</a></li>
                        <li class="divider"></li>
                        <li><a href="/Member/ExpRecord">我的积分</a></li>
                        <li class="divider"></li>
                        <li><a href="/Member/RebateRecord">我的返利</a></li>
                         <li class="divider"></li>
                        <li><a href="/Member/AddressBook">我的地址簿</a></li>
                        <li class="divider"></li>
                        <li><a href="/Member/UpdatePW">修改密码</a></li>
                    </ul>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div >  
             @{Html.RenderAction("Nav", "Common", new { type = 1 }); }          
        </div>
    <div id="container">@RenderBody()</div>
  
 <div class="foot">
<div class="about">关于诚配|网站公约|网站声明|帮助中心|联系我们|常见问题|网站地图</div>
<div class="copyring">我们在致力于打造中国最齐全的汽车配件用品市场!Cp文化网是汽车配件用品电商平台<br />我们能为您快速查找您需要的配件用品，同时提供最放心的交易平台</div>
<div class="copying2">Copyring @@ 2015 91CPCAR.com All Right Reserved &nbsp;&nbsp;版权所有&nbsp;&nbsp;湘ICP备15020410号 &nbsp</div> 
<div class="authentication">
			<a rel="nofollow" target="_blank" href="http://www.miitbeian.gov.cn/">
				<img width="103" height="32" alt="经营性网站备案中心" src="http://img12.360buyimg.com/da/jfs/t535/349/1185317137/2350/7fc5b9e4/54b8871eNa9a7067e.png" class="err-product">
			</a><a rel="nofollow" target="_blank" href="http://www.bj.cyberpolice.cn/index.do">
				<img width="103" height="32" alt="网络警察" src="http://img11.360buyimg.com/da/jfs/t559/186/1172042286/2795/7d90b036/54b8874bN694454a5.png" class="err-product">
			</a>
			<a rel="nofollow" target="_blank" href="http://www.szfw.org/">
				<img width="103" height="32" src="http://img11.360buyimg.com/da/jfs/t451/173/1189513923/1992/ec69b14a/54b8875fNad1e0c4c.png" class="err-product">
	<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://"); document.write(unescape("%3Cspan id='cnzz_stat_icon_1257109381'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1257109381%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
                	</a></div>
</div>
    </div>
    <div style="clear:both;"></div>
    <div>
     @Html.Partial("_ModalDiag")    
        </div>
</body>
</html>

 @RenderSection("scripts", required: false)  
<script  type="text/javascript" charset="utf-8">
    $(function () {
        $("#topsearch").click(function () {
            var kw = $("#txt_keyword").val();
            if (kw) {
                window.location.href = "/product/SearchProduct?keyword=" +encodeURI(kw);
            }
        })

        var keyword = getQueryString("keyword");
        if (keyword) {
            $("#txt_keyword").val(keyword);
            $(".paginator a").each(function () {
                var src = $(this).attr("href");
                $(this).attr("href", src + "&&keyword=" + $("#txt_keyword").val());
            })
        } else {
            $("#txt_keyword").val("");
        }

    })

</script>