CParts-Online/Models/Master/LoginModel.cs
using CommonUtils.Message;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CParts_Online.Models.Master
{
    public class LoginModel
    {
        /// <summary>
        /// 用户名
        /// </summary>
        [Required(ErrorMessage = ValidateMsg.requiredLoginName)]
        [StringLength(30, MinimumLength = 4, ErrorMessage = ValidateMsg.lengthLoginName)]
        public string loginName { get; set; }
        [Required(ErrorMessage = ValidateMsg.requiredPassWord)]
        [StringLength(20, MinimumLength = 8, ErrorMessage = ValidateMsg.lengthPassWord)]
        public string passWord { get; set; }
        /// <summary>
        /// 验证码
        /// </summary>
        [Required(ErrorMessage = ValidateMsg.requiredVeriCode)]
        [CustomValidation(typeof(ModelVaildate), "ValiCodeIsValid")]
        public string VeriCode { get; set; }



    }
}

CParts-Online/Models/Master/PartAttrModel.cs
using Cparts_service.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CParts_Offline.Models
{
    public class PartAttrOutModel
    {
        public string AttrName{ get; set; }      
        public int ParentAttr { get; set; }
        public List<DAO.PartsExtend> AttrList { get; set; }       
    }
    public class information
    {
        public string ID { get; set; }
        public int ordID { get; set; }
        public string wuliuhao { get; set; }
        public string isshouhuo { get; set; }
        public DateTime time { get; set; }
    }
  
}

CParts-Online/Models/Master/PartModel.cs
using Cparts_service.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CParts_Offline.Models
{
    public class PartOutModel
    {
        public List<PartSimpleModel> PartList { get; set; }
        public List<DAO.PartsCategory> PartCateList { get; set; }
        public List<DAO.PartBrand> PartBrandList { get; set; }
        public List<DAO.PartAttr> PartAttrList { get; set; }
        public List<DAO.PartStock> PartStockList { get; set; }
        public List<DAO.CarM> Cars { get; set; }
        public List<DAO.HotTable> ht { get; set; }
          public  int totleCount {get;set;}        
            public  int pageSize  {get;set;}
             public  int currentPage  {get;set;}
             public List<string> CarBrands { get; set; }
    }
    public class PartInBean
    {
     
        public string PartName { get; set; }
        public int  CategoryID { get; set; }
        public int PartBrand { get; set; }
        public int HotTable { get; set; }
        public string PartModel { get; set; }
        public string PartSuppyNo { get; set; }
        public decimal Price { get; set; }
        public int Orderby { get; set; }
        public int State { get; set; }
        public string ToCars { get; set; }
        public string Describe { get; set; }
        public string PartTitle { get; set; }
        public string PartSubtitle { get; set; }   
        public int StockNUM { get; set; }
        public string mDescribe { get; set; }
        public int ProType { get; set; }
        public string supply { get; set; }
        public string storeName { get; set; }
        public string material { get; set; }
        public string specifications { get; set; }
        public string useSite { get; set; }
        public string ParsColour { get; set; }
        //链接
        public string herf { get; set; }
        
    }
    public class info
    {
        public string ordID { get; set; }
        public string wuliuhao { get; set; }
    }
    public class wangzhi
    {
        public string ID { get; set; }
        public string pro { get; set; }
    }
}

CParts-Online/Controllers/master/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cparts_Service;
using CParts_Offline.Models;
using Cparts_service.Model;
using System.IO;
using CParts_Offline.Models.Master;
using CParts_Online.Models.Master;
using CParts_Online.Controllers.master;
using System.Text;
using ActiveModule;
using ProductModule.model;
using Cparts_service;
using MemberModule.Business;
using System.Net;
using System.Web.Script.Serialization;

namespace CParts_Offline.Controllers.master
{
    public class MasterController : Controller
    {

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginModel m)
        {
            //VerCode
            if (ModelState.IsValid)
            {
                MemberBll bll = new MemberBll();
                DAO.AdminAccount model = bll.Login(m.loginName, m.passWord);
                if (model != null)
                {
                    Session["AdminID"] = model.ID;
                    if (Session["ControllerUrl"] != null && Session["ActionUrl"] != null)
                    {
                        return RedirectToAction(Session["ActionUrl"].ToString(), Session["ControllerUrl"].ToString());
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ViewBag.loginFail = "用户名或密码错误！";
                    return View(m);
                }
            }
            else
            {

                return View(m);
            }
        }
        /// <summary>
        /// 订单列表
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
        [AdminFilter]        
        public ActionResult Index(SearchOrderParma parm)
        {
            OrderBll bll = new OrderBll();
            List<DAO.Order> orderList = bll.GetList(parm); //bll.GetList(null, "OrderTime", "desc");

            return View(orderList);
        }
        [AdminFilter]
        public ActionResult OrderDetail(string OrderNumber)
        {
            if (string.IsNullOrEmpty(OrderNumber))
            {
                return RedirectToAction("Index");
            }
            else
            {
                OrderBll oBll = new OrderBll();
                OrderDetail info = oBll.OrderDetail(OrderNumber);
                return View(info);
            }
        
        }

        /// <summary>
        /// 发货
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [AdminFilter]
        public ActionResult SendOrder(SendOrderBM bm)
        {
            Dictionary<string, object> map = new Dictionary<string, object>();
            try
            {
                ProductBll part = new ProductBll();
           
                DAO.Order orderS = part.selOrderId(bm.OrderNumber);

                List<DAO.OrderProList> orderList = part.selPartName(bm.OrderNumber);
                string ParsNames = "";

                for (int i = 0; i < orderList.Count(); i++)
                {
                    if (i == orderList.Count() - 1)
                    {
                        ParsNames += orderList[i].ProductName;
                    }
                    else
                    {
                        ParsNames += orderList[i].ProductName + ",";
                    }


                }

                OrderBll oBll = new OrderBll();
                bool r = oBll.SendOrder(bm);
                bool isPhone = PhoneNumber(orderS.CellPhone, bm.SandNumber, ParsNames);
                map.Add("status", r);
            }
            catch (Exception e)
            {
                map.Add("status", false);
                map.Add("msg", e.Message+e.StackTrace);
            }
            return Json(map,JsonRequestBehavior.AllowGet);
        }
        #region 汽车管理
        /// <summary>
        /// 汽车管理主页
        /// </summary>
        /// <returns></returns>
        [AdminFilter]
        public ActionResult CarsManage(string banner=null)
        {
            //汽车列表
            CarBll carbll = new CarBll();
            List<DAO.CarM> list;
            if (banner == "all" || string.IsNullOrEmpty(banner))
            {
                list = carbll.GetList();
            }
            else {
                list = carbll.GetList(banner);
            }
            return View(list);
        }
        /// <summary>
        /// 添加汽车
        /// </summary>
        /// <param name="car"></param>
        /// <returns></returns>
        [HttpPost]
        [AdminFilter]
        public ActionResult AddCar(DAO.CarM car)
        {
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            //添加汽车
            CarBll carbll = new CarBll();
            bool r = carbll.AddCar(car);
            if (r)
            {
                map.Add("result", "ok");
            }
            else
            {
                map.Add("result", "error");
            }
            return Json(map, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("CarsManage");
        }

        /// <summary>
        /// 修改汽车
        /// </summary>
        /// <param name="car"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditCar(DAO.CarM car)
        {
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            //修改汽车
            CarBll carbll = new CarBll();
            bool r = carbll.updateCar(car);
            if (r)
            {
                map.Add("result", "ok");
            }
            else
            {
                map.Add("result", "error");
            }
            return Json(map, JsonRequestBehavior.AllowGet);
            // return RedirectToAction("CarsManage");
        }


        [HttpPost]
        public ActionResult editg(DAO.Order edit)
        {
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            //修改汽车
             HotProductBll carbll = new HotProductBll();
             bool r = carbll.updatedz(edit);
            if (r)
            {
                map.Add("result", "ok");
            }
            else
            {
                map.Add("result", "error");
            }
            return Json(map, JsonRequestBehavior.AllowGet);
        }
        //
        /// <summary>
        /// 删除汽车
        /// </summary>
        /// <param name="car"></param>
        /// <returns></returns>
        [HttpPost]
        [AdminFilter]
        public ActionResult DelCar(string id)
        {
            //删除汽车
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            CarBll carbll = new CarBll();
            bool r = carbll.DelCar(id);
            if (r)
            {
                map.Add("result", "ok");
            }
            else
            {
                map.Add("result", "error");
            }
            return Json(map, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region 零部件分类管理

        /// <summary>
        ///零部件分类管理主页
        /// </summary>
        /// <returns></returns>
        [AdminFilter]
        public ActionResult PartsCateManage()
        {
            //列表
            PartsCateBll partbll = new PartsCateBll();
            PartCateViewModel vm = new PartCateViewModel();
            vm.PCItem = partbll.GetListPC();
            vm.AllItem = partbll.GetList();
            return View(vm);
        }
        /// <summary>
        /// 添加零部件分类管理
        /// </summary>
        /// <param name="car"></param>
        /// <returns></returns>
        [HttpPost]
        [AdminFilter]
        public ActionResult AddPartsCate(DAO.PartsCategory partcate)
        {
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            //添加
            PartsCateBll carbll = new PartsCateBll();
            bool r = carbll.Add(partcate);
            if (r)
            {
                map.Add("result", "ok");
            }
            else
            {
                map.Add("result", "error");
            }
            return Json(map, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("CarsManage");
        }

        /// <summary>
        /// 修改零部件分类管理
        /// </summary>
        /// <param name="car"></param>
        /// <returns></returns>
        [HttpPost]
        [AdminFilter]
        public ActionResult EditPartsCate(DAO.PartsCategory partcate)
        {
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            //修改
            PartsCateBll carbll = new PartsCateBll();
            bool r = carbll.Update(partcate);
            if (r)
            {
                map.Add("result", "ok");
            }
            else
            {
                map.Add("result", "error");
            }
            return Json(map, JsonRequestBehavior.AllowGet);
            // return RedirectToAction("CarsManage");
        }
        /// <summary>
        /// 产品分类ico图表图片
        /// </summary>
        /// <param name="Upimg"></param>
        /// <returns></returns>
        [HttpPost]
        [AdminFilter]
        public ActionResult AddPartsCImg(string Upimg)
        {

            HttpPostedFileBase file = Request.Files[0];
            string path = "/Upload/ICO/" + string.Format("{0:yyyyMMdd}", DateTime.Now) + "/";
            string uploadpath = Server.MapPath(path);
            if (file != null)
            {
                if (!Directory.Exists(uploadpath))
                {
                    Directory.CreateDirectory(uploadpath);
                }
            }
            file.SaveAs(uploadpath + file.FileName);

            PartsCateBll carbll = new PartsCateBll();
            DAO.PartsCategory model = carbll.GetModel(int.Parse(Upimg));

CParts-Online/Controllers/master/MasterMemberController.cs
using Cparts_Service;
using DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CParts_Offline.Controllers.master
{
    public class MasterMemberController : Controller
    {
        //
        // GET: /member/
        #region 会员等级
        
        public ActionResult memberLevel()
        {
            MemberLevelBll bll = new MemberLevelBll();
            List<MemberLevel> list= bll.GetList();
           // MemberLevel bll = new MemberLevel();
            return View(list);
        }
        /// <summary>
        /// 添加
        /// </summary>
        /// <param name="car"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Add(DAO.MemberLevel car)
        {
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            //添加汽车
            MemberLevelBll bll = new MemberLevelBll();
            bool r = bll.Add(car);
            if (r)
            {
                //map.Add("result", "ok");
            }
            else
            {
                //map.Add("result", "error");
            }
            return RedirectToAction("memberLevel");
           
        }
        /// <summary>
        /// 修改汽车
        /// </summary>
        /// <param name="car"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(DAO.MemberLevel car)
        {
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            //修改汽车
            MemberLevelBll bll = new MemberLevelBll();
            bool r = bll.update(car);
            return RedirectToAction("memberLevel");
        }
        /// <summary>
        /// 删除汽车
        /// </summary>
        /// <param name="car"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Del(string id)
        {
            //删除汽车
            Dictionary<string, Object> map = new Dictionary<string, Object>();
            MemberLevelBll carbll = new MemberLevelBll();
            bool r = carbll.Del(id);
            if (r)
            {
                map.Add("result", "ok");
            }
            else
            {
                map.Add("result", "error");
            }
            return Json(map, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 会员管理
        public ActionResult memberManage()
        {
            return View();
        }
        #endregion

    }
}

CParts-Online/Views/Master/ActiveDetail.cshtml
@model CParts_Online.Models.Master.ActiveDetailOM
    @{
        ViewBag.Title = "活动详情";
        Layout = "~/Views/Shared/_master.cshtml";
    }

    <div class="content-box">
        <!-- Start Content Box -->
        <div class="content-box-header2">
            <h3>活动详细</h3>
            <ul class="content-box-tabs">
                <li><a href="#tab1" class="default-tab">详情</a></li>
                <!-- href must be unique and match the id of target div -->
                <li><a href="#tab2" id="f1">添加</a></li>
                <li><a href="#tab3" id="tabEdit">编辑</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <!-- End .content-box-header -->
        <div class="content-box-content">
            <div class="tab-content default-tab" id="tab1">
                <h4>活动添加</h4>
                <table>
                    <tr>
                        <td>封面图片</td>
                        <td colspan="3">
                            <input type="file" value="选择图片" name="file" accept="image/*" />
                        </td>
                    </tr>
                    <tr>
                        <td>活动名称</td>
                        <td><input type="text" id="add_Act_Name" name="Name" /></td>
                        <td>活动代码</td>
                        <td><input type="text" id="add_Act_subName" name="SubName" /></td>
                    </tr>
                    <tr>
                        <td>开始时间</td>
                        <td>
                            <input type="text" readonly="true" class="text-input Wdate" onclick="WdatePicker()" id="add_Act_sdate" name="StarDate" />
                            <select id="add_Act_shour" class="dplist" name="shour"></select>
                            <select id="add_Act_smin" class="dplist" name="smin"></select>
                        </td>
                        <td>截止时间</td>
                        <td>
                            <input type="text" readonly="true" class="text-input Wdate" onclick="WdatePicker()" id="add_Act_edate" name="EndDate" />
                            <select id="add_Act_ehour" class="dplist" name="ehour"></select>
                            <select id="add_Act_emin" class="dplist" name="emin"></select>
                        </td>
                    </tr>
                    <tr>
                        <td>状态：</td>
                        <td><select id="add_Act_status" name="Status"><option value="0">终止</option><option value="1" selected>正常</option></select></td>
                    </tr>
                    <tr>
                        <td colspan="4"><button id="btn-add" type="submit">保存活动</button></td>
                    </tr>
                </table>
                <br />
                        <div >
                            <h3>活动产品</h3>
                            <select>
                                <option value="1" >P1</option>
                                <option value="2">P1</option>
                            </select>
                        </div>
                        <div id="act_pro_list">
                                <div id="pro_1">
                                     <div class="pro_title">p1</div>
                                    <div class="pro_content" style="display:none" >
                                      <br />
                                        p2222
                                        <br />
                                    </div>
                                </div>
                        </div>










                </div>
            </div>
  </div>
@section scripts{
    <script>
        $(function () {
            $(".pro_title").click(function () {
                $(this).siblings(".pro_content").toggle();
            });
        })
    </script>
    
    }

CParts-Online/Views/Master/Index.cshtml
@model IEnumerable<DAO.Order>
@{
    ViewBag.Title = "";
   // Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/_master.cshtml";
}
@section scripts
{
   <script language="javascript" type="text/javascript" src="/resources/scripts/My97DatePicker/WdatePicker.js"></script>
    <script>
        $(function () {
            $("#orderStatus,#payStatus").change(function () {
                $("#OrderForm").submit();
            })
            $("#orderTable tr").hover(function () {
                $(this).addClass("hover");
            }, function () {
                $(this).removeClass("hover");
            })

            $("#saveCa").click(function () {
                // showdiv('正在保存中***');
                var name = $("#ordID").val();
                var isB = $("#wuliuhao").val();
                var level = {
                    Name: name,
                    wuliuhao: isB
                };
                $("#form_addActive").submit();

            });


        })

        function myclick(str) {
            $("#ordID").val(str);
            Post("/Master/wuliuhapas/", { "ordID": str }, function (data, error) {
                if (data.name=="0") {
                    $("#tab1").hide();
                    $("#tab2").show();
                }
                else {
                    $("#wuliuhao").val(data.name)
                     $("#tab1").hide();
                    $("#tab2").show();
                }
                
            })
        }
    </script>
  
}
@section styles{
      <link href="/resources/scripts/My97DatePicker/skin/WdatePicker.css" rel="stylesheet" type="text/css">
    <style>
        .hover {
        background:#b8eba5 !important;
        }
        #orderTable a {
         display:block;
         padding:5px;
         width:50px;
        }
    </style>
    }
  
<div class="content-box">
    <!-- Start Content Box -->
    <div class="content-box-header2">
        <h3>订单管理</h3>
        <ul class="content-box-tabs">
            <li><a href="#tab1" class="default-tab">所有列表</a></li>
            <!-- href must be unique and match the id of target div -->
            <li><a href="#tab2" id="f1">添加</a></li>
            <li><a href="#tab3" id="tabEdit">编辑</a></li>
        </ul>
        <div class="clear"></div>
    </div>
    <!-- End .content-box-header -->
    <div class="content-box-content">
        <div class="tab-content default-tab" id="tab1">
            <div>
              @using (Html.BeginForm("Index", "Master", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "OrderForm" }))
   {
                <div class="bulk-actions">
                    订单状态: 
                    <select name="orderStatus" id="orderStatus">
                        <option value="all">--所有--</option>
                        <option value="未处理">未处理</option>
                        <option value="已发货">已发货</option>                        
                        <option value="已完成">已完成</option>
                        <option value="已作废">已作废</option>
                    </select>&nbsp;&nbsp;
                     支付状态:
                    <select  name="payStatus" id="payStatus">
                        <option value="all">--所有--</option>
                        <option value="已支付">已支付</option>
                        <option value="未支付">未支付</option>                        
                    </select>&nbsp;&nbsp;
                     订单号：<input type="text" class="text-input" name="orderNumber"/>
                    <button class="button"   type="submit">搜索</button>
                    姓名：<input type="text" class="text-input" name="consignee"/>
                    <button class="button"   type="submit">搜索</button>
                     从：<input type="text" readonly="true" class="text-input Wdate" onclick="WdatePicker()" name="orderBeginTime"/>
                     到：<input type="text" readonly="true" class="text-input Wdate" onclick="WdatePicker()" name="orderEndTime"/>
                    <button class="button"  type="submit">搜索</button>
                </div>
              }

            </div>
            <div style="width:50%">
            
                </div>
          <table width="100%" id="orderTable">
                <thead>
                    <tr>
                        <th valign="middle">订单ID</th>
                        <th valign="middle">订单号</th>
                        <th valign="middle">下单用户</th>   
                        <th valign="middle">下单昵称</th>                      
                      @*  <th valign="middle">商品总数</th>  *@
                        <th valign="middle">订单金额</th>
                        <th valign="middle">下单日期</th> 
                        <th valign="middle">支付状态</th>    
                        <th valign="middle">订单状态</th>   
                        <th valign="middle">快递公司</th>  
                        <th valign="middle">快递单号</th>    
                        <th>操作</th>                 
                    </tr>
                    
                </thead>
               
                <tbody style="font-size: 14px">
                    @foreach (var item in Model)
                    {
                         <tr>
                        <td >@item.ID</td>
                        <td >@item.OrderId</td>
                             <td >@item.Consignee</td>   
                        <td >@item.UserName</td>                        
                         @*  <th valign="middle">商品总数</th>  *@ 
                        <td >@item.TotalPrice.ToString(".00")</td>
                        <td >@item.OrderTime</td> 
                        <td > @if (item.PayStatus=="未支付")
                                {
                                  <a href="javascript:void(0)" style="color:#000;" >未支付</a>
                                }
                                else{
                                 <a href="javascript:void(0)" style="color:#fff; background:red; ">@item.PayStatus</a>
                                }</td>    
                        <td >
                            @if (item.PayStatus == "已支付")
                            {
                                if (item.OrderStatus == "未处理")
                                {
                                <a href="javascript:void(0)" style="color:#fff; background:red;" >@item.OrderStatus</a> 
                                }
                                if (item.OrderStatus == "已发货")
                                {
                                <a href="javascript:void(0)" style="color:#fff; background:#ff6a00;" >@item.OrderStatus</a> 
                                }
                                if (item.OrderStatus == "已完成")
                                {
                                <a href="javascript:void(0)" style="color:#fff;background:green;" >@item.OrderStatus</a> 
                                }
                                if (item.OrderStatus == "已处理")
                                {
                                     <a href="javascript:void(0)" style="color:#fff;background:green;" >@item.OrderStatus</a> 
                                }
                            }else{
                            @item.OrderStatus
                            }
                        </td>    
                              <td>@item.SendName</td>   
                              <td>@item.SendNum</td>   
                        <td><input type="hidden" id="h1" value="" />
                            <a class="button" target="_blank" href="/Master/OrderDetail?OrderNumber=@(item.OrderId)">订单详细</a>&nbsp;&nbsp;&nbsp;&nbsp;<a class="button" href="javascript:void(0)" onclick="myclick('@(item.OrderId)')" id="a1" target="_blank">修改状态</a>
                        <a class="button" onclick="edclick('@(item.OrderId)')" id="chuli"  >删除</a>
                        </td>         
                    </tr>
                    }
                    
                </tbody>
            </table>
        </div>
       
            <div class="tab-content" id="tab2" style="width: 100%;display:none" >
            <form id="form_addActive" method="post" action="/Master/wuliupart">
                <table>
                           <tr>
                        <td>订单号:</td>
                        <td>
                            <input type="text" name="ordID" id="ordID" readonly="readonly" ><span style="color:red">*</span>
                        </td>
                    </tr>
                          <tr>
                        <td>物流号:</td>
                        <td>
                            <input type="text" name="wuliuhao" id="wuliuhao">
                        </td>
                    <tr>
                    <tfoot>
                        <tr>
                            <td>
                                <input type="button" id="saveCa" value="       添加      " class="button" /></td>
                        </tr>

                    </tfoot>
                   
                </table>
                </form>
                <div class="clear"></div>
         
        </div>


         <div class="tab-content" id="tab3" style="width: 100%">

             
         

        </div>
        <!-- End #tab2 -->
    </div>
    <!-- End .content-box-content -->
</div>
<script>
    ///更新状态
    function edclick(str) {
        if (confirm("确定要更新？")) {
            Post("/Master/editzt/", { 'OrderId': str }, function (data, error) {
                if (data.status == 'ok') {
                    alert(data.msg);
                    location.href = "/master/index";
                }
                else {
                    alert(data.msg);
                }

            })
        }
    }
 
 
</script>